---
apiVersion: v1
kind: Service
metadata:
  name: dns-tcp-svc-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-public-ip
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: dns-udp-svc-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-public-ip
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
