---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: dev
subjects:
- kind: User
  name: ken
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
